---
# Dynamically generated inventory by Thinkube Installer

all:
  vars:
    domain_name: "thinkube.com"
    admin_username: "tkadmin"
    system_username: "thinkube"
    auth_realm_username: "thinkube"
    ansible_python_interpreter: "/home/thinkube/.venv/bin/python3"
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_SUDO_PASS') }}"
    home: "{{ lookup('env', 'HOME') }}"
    network_cidr: "192.168.1.0/24"
    network_gateway: "192.168.1.1"
    zerotier_network_id: "93afae59634c1a70"
    zerotier_api_token: "XusunDVtdaDF6BY4EDohb65H5UXi3isq"
    zerotier_cidr: "192.168.191.0/24"
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    lxd_network_name: "lxdbr0"
    lxd_network_ipv4_address: "192.168.100.1/24 (auto-configured)"
    lxd_network_ipv6_address: "none"
    cloudflare_token: "3KA3H_ER9Yc7Jp2xr-ETKV7m8mOar4U5mCtdMibA"
  children:
    baremetal:
      hosts:
        bcn1:
          ansible_host: "192.168.1.101"
          lan_ip: "192.168.1.101"
          zerotier_ip: "192.168.191.10"
          arch: "x86_64"
          zerotier_enabled: true
          ansible_connection: "local"
          configure_gpu_passthrough: true
        bcn2:
          ansible_host: "192.168.1.102"
          lan_ip: "192.168.1.102"
          zerotier_ip: "192.168.191.11"
          arch: "x86_64"
          zerotier_enabled: true
          configure_gpu_passthrough: false
    lxd_cluster:
      children:
        lxd_primary:
          hosts:
            bcn2:
        lxd_secondary:
          hosts:
            bcn1:
    dns:
      hosts:
        dns1:
    microk8s:
      children:
        microk8s_control_plane:
          hosts:
            bcn2:
        microk8s_workers:
          hosts:
            bcn1:
            tkw1:
    lxd_containers:
      vars:
        lxd_image: "ubuntu:24.04"
        ansible_python_interpreter: "/home/thinkube/.venv/bin/python3"
      children:
        dns_containers:
          hosts:
            dns1:
              parent_host: "bcn2"
              memory: "2GB"
              cpu_cores: 2
              disk_size: "20GB"
              arch: "x86_64"
              lan_ip: "192.168.1.112"
              internal_ip: "192.168.100.10"
              zerotier_ip: "192.168.191.1"
              zerotier_enabled: true
              gpu_passthrough: false
        microk8s_containers:
          children:
            controllers:
              hosts:
            workers:
              hosts:
                tkw1:
                  parent_host: "bcn1"
                  memory: "48GB"
                  cpu_cores: 12
                  disk_size: "500GB"
                  arch: "x86_64"
                  lan_ip: "192.168.1.113"
                  internal_ip: "192.168.100.11"
                  zerotier_ip: "192.168.191.13"
                  zerotier_enabled: true
                  gpu_passthrough: true