---
# Dynamically generated inventory by Thinkube Installer

all:
  vars:
    domain_name: "thinkube.com"
    admin_username: "tkadmin"
    system_username: "thinkube"
    auth_realm_username: "thinkube"
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_BECOME_PASSWORD') }}"
    home: "{{ lookup('env', 'HOME') }}"
    network_cidr: "192.168.1.0/24"
    network_gateway: "192.168.1.1"
    zerotier_network_id: "93afae59634c1a70"
    zerotier_api_token: "X6jbboirhv4oCIOFM3WWUSBgM7qrI1z2"
    zerotier_cidr: "192.168.191.0/24"
    zerotier_subnet_prefix: "192.168.191."
    primary_ingress_ip_octet: "200"
    secondary_ingress_ip_octet: "201"
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"
    dns_search_domains:
    lxd_network_name: "lxdbr0"
    lxd_network_ipv4_address: "192.168.100.1/24"
    lxd_network_ipv6_address: "none"
    internal_gateway: "192.168.100.1"
    cloudflare_token: "w95KIVRILvb-srJkOLK_qMqlOVZMXBgT1oKsO_ue"
  children:
    arch:
      children:
        x86_64:
          hosts:
            bcn1:
            dns:
            vm-2:
        arm64:
          hosts:
    baremetal:
      hosts:
        bcn1:
          ansible_host: "192.168.1.101"
          lan_ip: "192.168.1.101"
          zerotier_ip: "192.168.191.10"
          arch: "x86_64"
          zerotier_enabled: true
          ansible_connection: "local"
          configure_gpu_passthrough: true
          assigned_pci_slots:
            - "01:00.0"
      children:
        headless:
          hosts:
        desktops:
          hosts:
            bcn1:
        dgx:
          hosts:
    lxd_cluster:
      children:
        lxd_primary:
          hosts:
            bcn1:
        lxd_secondary:
          hosts:
    dns_servers:
      hosts:
        dns:
    microk8s:
      children:
        microk8s_control_plane:
          hosts:
            vm-2:
        microk8s_workers:
          hosts:
            bcn1:
    lxd_containers:
      vars:
        lxd_image: "ubuntu:24.04"
        ansible_python_interpreter: "/home/thinkube/.venv/bin/python3"
      children:
        dns_vms:
          hosts:
            dns:
              parent_host: "bcn1"
              memory: "2GB"
              cpu_cores: 2
              disk_size: "20GB"
              arch: "x86_64"
              lan_ip: "192.168.1.111"
              internal_ip: "192.168.100.10"
              zerotier_ip: "192.168.191.1"
              zerotier_enabled: true
              gpu_passthrough: false
        microk8s_containers:
          children:
            controllers:
              hosts:
                vm-2:
                  parent_host: "bcn1"
                  memory: "48GB"
                  cpu_cores: 12
                  disk_size: "500GB"
                  arch: "x86_64"
                  lan_ip: "192.168.1.112"
                  internal_ip: "192.168.100.11"
                  zerotier_ip: "192.168.191.12"
                  zerotier_enabled: true
                  gpu_passthrough: true
                  pci_slot: "0000:01:00.0"
            workers:
              hosts:
    zerotier_nodes:
      hosts:
        bcn1:
        dns:
        vm-2:
    management:
      hosts:
        bcn1:
    gpu_passthrough_vms:
      hosts:
        vm-2:
    container_configs:
      vars:
    baremetal_gpus:
      vars: