---
# Shell Configuration - Configure all shells to load functions and aliases

# Configure Bash for Thinkube
- name: Configure Bash for Thinkube
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    marker: "# {mark} THINKUBE SHELL FUNCTIONS"
    insertafter: EOF
    block: |
      # Initialize Starship prompt
      if command -v starship >/dev/null 2>&1; then
          eval "$(starship init bash)"
      fi
      
      # Load Thinkube shared functions and aliases
      if [ -f "{{ thinkube_system_dir }}/load_functions.sh" ]; then
          source "{{ thinkube_system_dir }}/load_functions.sh"
      fi
      
      # Load shared aliases function (which loads the actual aliases)
      if [ -f "{{ thinkube_system_functions_dir }}/load_aliases.sh" ]; then
          source "{{ thinkube_system_functions_dir }}/load_aliases.sh"
      fi
  tags: [bash, thinkube]

# Configure Zsh for Thinkube
- name: Ensure zsh config file exists
  file:
    path: "{{ user_home }}/.zshrc"
    state: touch
    mode: '0644'
  tags: [zsh, thinkube]

- name: Configure Zsh for Thinkube
  blockinfile:
    path: "{{ user_home }}/.zshrc"
    marker: "# {mark} THINKUBE SHELL FUNCTIONS"
    insertafter: EOF
    block: |
      # Initialize Starship prompt
      if command -v starship >/dev/null 2>&1; then
          eval "$(starship init zsh)"
      fi
      
      # Load Thinkube shared functions
      if [ -f "{{ thinkube_system_dir }}/load_functions.sh" ]; then
          source "{{ thinkube_system_dir }}/load_functions.sh"
      fi
      
      # Load shared aliases function (which loads the actual aliases)
      if [ -f "{{ thinkube_system_functions_dir }}/load_aliases.sh" ]; then
          source "{{ thinkube_system_functions_dir }}/load_aliases.sh"
      fi
  tags: [zsh, thinkube]

# Configure Fish for Thinkube
- name: Ensure fish config directory exists
  file:
    path: "{{ fish_config_dir }}"
    state: directory
    mode: '0755'
  tags: [fish, thinkube]

- name: Ensure fish config file exists
  file:
    path: "{{ fish_config_dir }}/config.fish"
    state: touch
    mode: '0644'
  tags: [fish, thinkube]

- name: Configure Fish for Thinkube
  blockinfile:
    path: "{{ fish_config_dir }}/config.fish"
    marker: "# {mark} THINKUBE SHELL FUNCTIONS"
    insertafter: EOF
    block: |
      # Initialize Starship prompt
      if command -v starship >/dev/null 2>&1
          starship init fish | source
      end
      
      # Load Thinkube shared functions
      if test -f "{{ thinkube_system_dir }}/load_functions.fish"
          source "{{ thinkube_system_dir }}/load_functions.fish"
      end
      
      # NOTE: Aliases are now loaded by the functions loader
      # Do not load aliases separately to avoid recursive loading
  tags: [fish, thinkube]