---
- name: Test Keycloak Credentials
  hosts: microk8s_control_plane
  gather_facts: false
  
  vars:
    admin_password: "{{ lookup('env', 'ADMIN_PASSWORD') | default(lookup('file', '~/.env') | regex_search('ADMIN_PASSWORD=(.+)', '\\1') | first, true) }}"
    
  tasks:
    - name: Test login via container exec
      ansible.builtin.shell: |
        POD_NAME=$(microk8s kubectl get pods -n keycloak -o jsonpath='{.items[0].metadata.name}')
        microk8s kubectl exec -n keycloak $POD_NAME -- \
          curl -s -X POST "http://localhost:8080/realms/master/protocol/openid-connect/token" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=password&client_id=admin-cli&username=admin&password={{ admin_password }}"
      register: login_result
      become: true
      
    - name: Show login result
      ansible.builtin.debug:
        var: login_result.stdout