apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-builder
  namespace: argo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kaniko-builder-role
  namespace: argo
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kaniko-builder-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: kaniko-builder
  namespace: argo
roleRef:
  kind: Role
  name: kaniko-builder-role
  apiGroup: rbac.authorization.k8s.io
