---
# 20_setup_env.yaml - Set up environment variables from inventory
#
# Purpose:
#   Creates environment variables file from inventory settings,
#   preserving any existing variables not set by inventory.
#
# Requirements:
#   - SSH keys must be configured correctly
#   - Inventory file must contain required variables
#
# Variables:
#   Required (from inventory):
#     - domain_name: Primary domain for services
#     - network_cidr: IP range for the network
#     - network_gateway: Default gateway for LAN
#     - admin_username: Administrative username
#   Optional:
#     - zerotier_network_id: ZeroTier network identifier
#
# Run with: 
#   ansible-playbook -i inventory/inventory.yaml ansible/00_initial_setup/20_setup_env.yaml
#   Or with helper script:
#   ./scripts/run_ansible.sh ansible/00_initial_setup/20_setup_env.yaml

- name: Setup Environment Variables from Inventory
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Verify required variables
      ansible.builtin.assert:
        that:
          - domain_name is defined and domain_name | length > 0
          - network_cidr is defined and network_cidr | length > 0
          - network_gateway is defined and network_gateway | length > 0
          - admin_username is defined and admin_username | length > 0
        fail_msg: |
          ERROR: Missing Required Variables
          
          DETAILS:
          - The following variables must be defined in inventory:
            - domain_name: {% if domain_name is defined and domain_name | length > 0 %}✓{% else %}✗ missing{% endif %}
            - network_cidr: {% if network_cidr is defined and network_cidr | length > 0 %}✓{% else %}✗ missing{% endif %}
            - network_gateway: {% if network_gateway is defined and network_gateway | length > 0 %}✓{% else %}✗ missing{% endif %}
            - admin_username: {% if admin_username is defined and admin_username | length > 0 %}✓{% else %}✗ missing{% endif %}
          
          REQUIRED ACTION:
          - Add missing variables to your inventory file at inventory/inventory.yaml
          - Or define them in inventory/group_vars/all.yml
          
          REFERENCE: See docs/architecture/VARIABLE_HANDLING.md
    - name: Check if .env file already exists
      ansible.builtin.stat:
        path: "{{ lookup('env', 'HOME') }}/.env"
      register: env_file

    - name: Backup existing .env file if it exists
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.env"
        dest: "{{ lookup('env', 'HOME') }}/.env.bak"
        mode: '0600'
        remote_src: yes
      when: env_file.stat.exists
      
    - name: Read existing .env file if it exists
      ansible.builtin.slurp:
        src: "{{ lookup('env', 'HOME') }}/.env"
      register: existing_env
      when: env_file.stat.exists
      
    - name: Create a temporary file with existing environment variables
      ansible.builtin.copy:
        content: "{{ existing_env['content'] | b64decode }}"
        dest: "/tmp/env_parse_temp"
        mode: '0600'
      when: env_file.stat.exists and existing_env is defined

    - name: Extract variable names from env file
      ansible.builtin.shell: |
        grep -v "^#" /tmp/env_parse_temp | grep "=" | sed 's/=.*//' | tr -d ' '
      register: var_names
      when: env_file.stat.exists and existing_env is defined
      
    - name: Create a dictionary with existing variables
      ansible.builtin.set_fact:
        existing_env_vars: "{{ existing_env_vars | default({}) | combine({ item: lookup('env', item) }) }}"
      with_items: "{{ var_names.stdout_lines | default([]) }}"
      when: env_file.stat.exists and existing_env is defined and var_names.stdout_lines | default([]) | length > 0
      
    # Removed redundant dictionary initialization and processing steps
      
    - name: Create .env file while preserving existing variables
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/env_file.j2"
        dest: "{{ lookup('env', 'HOME') }}/.env"
        mode: '0600'
      vars:
        existing_variables: "{{ existing_env_vars | default({}) }}"
      
    - name: Display environment setup message
      ansible.builtin.debug:
        msg: "Environment variables have been set up in ~/.env"
        
    - name: Remind to source the environment file
      ansible.builtin.debug:
        msg: "Remember to run 'source ~/.env' to load these variables in your current shell"
        
    - name: Clean up temporary files
      ansible.builtin.file:
        path: "/tmp/env_parse_temp"
        state: absent
      when: env_file.stat.exists and existing_env is defined

    - name: Create symbolic link to .env file in project root
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/.env"
        dest: "{{ playbook_dir }}/../../.env"
        state: link
        force: yes

    - name: Check if executable script exists for environment sourcing
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/../../scripts/setup_env_link.sh"
      register: setup_script

    - name: Display successful setup message
      ansible.builtin.debug:
        msg: >-
          
          ═════════════════════════════════════════════════════════
          ✓ Environment Setup Complete
          ═════════════════════════════════════════════════════════
          
          Environment variables have been successfully set up.
          
          DETAILS:
            ✓ Created ~/.env file with required variables
            ✓ Created symbolic link in project root
            ✓ Preserved existing custom variables
          
          NEXT STEPS:
            1. Source the environment file: source ~/.env
            2. Verify variables are loaded: echo $DOMAIN_NAME
          
          ═════════════════════════════════════════════════════════