---
# 19_restore_direct_network.yaml - Restore direct network connectivity with fixed IPs
#
# Purpose:
#   Removes network bridge (br0) and restores direct interface connectivity
#   with FIXED IP addresses from inventory, not DHCP.
#
# Run with: 
#   ansible-playbook -i inventory/inventory.yaml ansible/10_baremetal_infra/19_restore_direct_network.yaml
#   Or with helper script:
#   ./scripts/run_ansible.sh ansible/10_baremetal_infra/19_restore_direct_network.yaml

- name: Restore Direct Network Connectivity with Fixed IPs
  hosts: baremetal
  gather_facts: true
  become: true
  vars:
    network_bridge_name: "br0"
    ansible_become_pass: "{{ lookup('env', 'ANSIBLE_SUDO_PASS') }}"
    
  tasks:
    - name: Display critical warning message
      ansible.builtin.debug:
        msg: >-
          
          ═════════════════════════════════════════════════════════
          🚨 CRITICAL ACTION: Direct Network Restoration ({{ inventory_hostname }}) 🚨
          ═════════════════════════════════════════════════════════
          
          This playbook will:
          1. Remove any existing network bridge ({{ network_bridge_name }})
          2. Restore direct network connectivity using the physical interface
          3. Configure a FIXED IP address: {{ ansible_host }}
          
          WARNING: This will likely disrupt your SSH connection temporarily.
          
          ═════════════════════════════════════════════════════════
    
    # Critical user confirmation
    - name: Confirm before proceeding
      ansible.builtin.pause:
        prompt: "Press ENTER to proceed with network restoration or Ctrl+C to abort"
    
    # Backup current network configuration
    - name: Backup current network configuration state to /tmp
      ansible.builtin.shell: |
        ip a > /tmp/network_before_restore_{{ ansible_date_time.epoch }}.txt
        ip r > /tmp/routes_before_restore_{{ ansible_date_time.epoch }}.txt
        if [ -d /etc/netplan ]; then
          mkdir -p /tmp/netplan_backup_{{ ansible_date_time.epoch }}
          cp -a /etc/netplan/* /tmp/netplan_backup_{{ ansible_date_time.epoch }}/
        fi
      changed_when: false
      
    - name: Display backup location
      ansible.builtin.debug:
        msg: "Network configuration backed up to /tmp/netplan_backup_{{ ansible_date_time.epoch }}/"
    
    # Determine primary network interface
    - name: Determine primary network interface
      ansible.builtin.shell: |
        # First try from route info
        PRIMARY_IFACE=$(ip route get 8.8.8.8 2>/dev/null | grep -oP 'dev \K\S+' | head -1)
        
        # If using bridge, try to find physical interface
        if [ "$PRIMARY_IFACE" = "{{ network_bridge_name }}" ]; then
          # Look for physical interfaces that might be attached to bridge
          PRIMARY_IFACE=$(ip -o link show | grep -v "lo\|{{ network_bridge_name }}\|veth\|docker" | head -1 | awk -F': ' '{print $2}')
        fi
        
        # If still no interface found, try more general approach
        if [ -z "$PRIMARY_IFACE" ] || [ "$PRIMARY_IFACE" = "{{ network_bridge_name }}" ]; then
          PRIMARY_IFACE=$(ip -o link show | grep -v "lo\|{{ network_bridge_name }}\|veth\|docker" | grep "state UP" | head -1 | awk -F': ' '{print $2}' || ip -o link show | grep -v "lo\|{{ network_bridge_name }}\|veth\|docker" | head -1 | awk -F': ' '{print $2}')
        fi
        
        echo "$PRIMARY_IFACE"
      register: primary_interface_result
      changed_when: false
      
    - name: Set primary interface fact
      ansible.builtin.set_fact:
        primary_interface: "{{ primary_interface_result.stdout }}"
      
    - name: Verify primary interface was determined
      ansible.builtin.assert:
        that:
          - primary_interface != ""
          - primary_interface != network_bridge_name
        fail_msg: |
          ERROR: Could not determine primary physical network interface
          
          DETAILS:
          - Unable to identify the physical network interface (not the bridge)
          - This is required to restore direct connectivity
          
          REQUIRED ACTION:
          - Run the playbook with a specific interface:
            ansible-playbook -i inventory/inventory.yaml ansible/10_baremetal_infra/19_restore_direct_network.yaml -e "primary_interface=eth0"
    
    - name: Display detected interface
      ansible.builtin.debug:
        msg: "Detected physical interface: {{ primary_interface }}"
    
    # Get required network information from inventory
    - name: Verify required network variables
      ansible.builtin.assert:
        that:
          - ansible_host is defined
          - network_gateway is defined
        fail_msg: |
          ERROR: Missing Required Variables
          
          DETAILS:
          - The following variables must be defined in inventory:
            - ansible_host: {% if ansible_host is defined %}✓{% else %}✗ missing{% endif %}
            - network_gateway: {% if network_gateway is defined %}✓{% else %}✗ missing{% endif %}
          
          REQUIRED ACTION:
          - Add missing variables to your inventory file at inventory/inventory.yaml
    
    # Check if bridge interface exists
    - name: Check if bridge interface exists
      ansible.builtin.shell: ip link show {{ network_bridge_name }} 2>/dev/null || echo "NOT_FOUND"
      register: bridge_check
      changed_when: false
      
    # Remove bridge if it exists
    - name: Take down bridge interface if it exists
      ansible.builtin.command: ip link set dev {{ network_bridge_name }} down
      when: bridge_check.stdout != "NOT_FOUND"
      register: bridge_down
      changed_when: bridge_down.rc == 0
      failed_when: false
      
    - name: Delete bridge interface if it exists
      ansible.builtin.command: ip link delete {{ network_bridge_name }}
      when: bridge_check.stdout != "NOT_FOUND"
      register: bridge_delete
      changed_when: bridge_delete.rc == 0
      failed_when: false
    
    # Create direct network configuration with fixed IP
    - name: Create netplan configuration with fixed IP
      ansible.builtin.template:
        src: simple-netplan.yaml.j2
        dest: /etc/netplan/01-thinkube-config.yaml
        mode: '0600'
        owner: root
        group: root
      vars:
        interface_name: "{{ primary_interface }}"
        ip_address: "{{ ansible_host }}"
        gateway: "{{ network_gateway }}"
      
    - name: Final warning before applying network changes
      ansible.builtin.debug:
        msg: >-
          
          ⚠️  FINAL WARNING ⚠️  NETWORK DISRUPTION IMMINENT ⚠️
          
          About to apply network changes:
          1. Remove bridge {{ network_bridge_name }} (if it exists)
          2. Configure interface {{ primary_interface }} with fixed IP {{ ansible_host }}
          
          YOUR SSH CONNECTION WILL BE DISRUPTED TEMPORARILY.
          
          After network changes are applied:
          1. Wait for the SSH session to time out
          2. Reconnect to the server at {{ ansible_host }}
          
    # Apply network configuration - will disconnect SSH temporarily
    - name: Apply netplan configuration (WILL DISCONNECT SSH TEMPORARILY)
      ansible.builtin.shell: |
        # Apply the configuration
        netplan apply
        
        # Return success
        echo "Netplan configuration applied"
      async: 60  # Run asynchronously
      poll: 0    # Don't wait for completion