---
- name: Rollback DNS resolution configuration
  hosts: all
  become: no  # Set per task as needed
  gather_facts: true

  tasks:
    - name: Restore default systemd-resolved configuration
      block:
        - name: Remove custom resolved.conf
          ansible.builtin.file:
            path: /etc/systemd/resolved.conf
            state: absent
          become: true

        - name: Restore default resolved.conf
          ansible.builtin.command: |
            cp /usr/lib/systemd/resolv.conf /etc/systemd/resolved.conf
          become: true
          changed_when: true

        - name: Restart systemd-resolved
          ansible.builtin.systemd:
            name: systemd-resolved
            state: restarted
            daemon_reload: true
          become: true

    - name: Remove LXD DNS configuration
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: ConfigMap
        name: lxd-dns-config
        namespace: kube-system
      when: "'k8s-control-node' in group_names"
      run_once: true

    - name: Reset LXD container DNS policies
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        merge_type: merge
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ item }}"
            namespace: "{{ item_namespace | default('default') }}"
          spec:
            template:
              spec:
                dnsPolicy: ClusterFirst
                dnsConfig: null
      loop: "{{ lxd_containers_in_k8s | default([]) }}"
      when: "'k8s-control-node' in group_names"
      run_once: true